// @ts-nocheck
/**
 * @fileoverview AUTOGENERATED — Do not edit directly.
 * Source: web-features compat_features → descriptor DSL (strict-safe subset).
 */

import type { Descriptor } from "../types";

const descriptors: ReadonlyArray<Descriptor> = [
  {
    "featureId": "accessor-methods",
    "kind": "callStatic",
    "base": "Object",
    "prop": "defineGetter"
  },
  {
    "featureId": "accessor-methods",
    "kind": "callStatic",
    "base": "Object",
    "prop": "defineSetter"
  },
  {
    "featureId": "accessor-methods",
    "kind": "callStatic",
    "base": "Object",
    "prop": "lookupGetter"
  },
  {
    "featureId": "accessor-methods",
    "kind": "callStatic",
    "base": "Object",
    "prop": "lookupSetter"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "Array"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "concat"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "join"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "length"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "pop"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "push"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "reverse"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "shift"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "slice"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "sort"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "toString"
  },
  {
    "featureId": "array",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "unshift"
  },
  {
    "featureId": "array-at",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "at"
  },
  {
    "featureId": "array-by-copy",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "toReversed"
  },
  {
    "featureId": "array-by-copy",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "toSorted"
  },
  {
    "featureId": "array-by-copy",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "toSpliced"
  },
  {
    "featureId": "array-by-copy",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "with"
  },
  {
    "featureId": "array-copywithin",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "copyWithin"
  },
  {
    "featureId": "array-fill",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "fill"
  },
  {
    "featureId": "array-find",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "find"
  },
  {
    "featureId": "array-find",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "findIndex"
  },
  {
    "featureId": "array-findlast",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "findLast"
  },
  {
    "featureId": "array-findlast",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "findLastIndex"
  },
  {
    "featureId": "array-flat",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "flat"
  },
  {
    "featureId": "array-flat",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "flatMap"
  },
  {
    "featureId": "array-from",
    "kind": "callStatic",
    "base": "Array",
    "prop": "from"
  },
  {
    "featureId": "array-fromasync",
    "kind": "callStatic",
    "base": "Array",
    "prop": "fromAsync"
  },
  {
    "featureId": "array-group",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "groupBy"
  },
  {
    "featureId": "array-group",
    "kind": "callStatic",
    "base": "Object",
    "prop": "groupBy"
  },
  {
    "featureId": "array-includes",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "includes"
  },
  {
    "featureId": "array-isarray",
    "kind": "callStatic",
    "base": "Array",
    "prop": "isArray"
  },
  {
    "featureId": "array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "every"
  },
  {
    "featureId": "array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "filter"
  },
  {
    "featureId": "array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "forEach"
  },
  {
    "featureId": "array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "indexOf"
  },
  {
    "featureId": "array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "lastIndexOf"
  },
  {
    "featureId": "array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "map"
  },
  {
    "featureId": "array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "reduce"
  },
  {
    "featureId": "array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "some"
  },
  {
    "featureId": "array-iterators",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "@@iterator"
  },
  {
    "featureId": "array-iterators",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "entries"
  },
  {
    "featureId": "array-iterators",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "keys"
  },
  {
    "featureId": "array-iterators",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "values"
  },
  {
    "featureId": "array-of",
    "kind": "callStatic",
    "base": "Array",
    "prop": "of"
  },
  {
    "featureId": "array-splice",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "splice"
  },
  {
    "featureId": "atomics-pause",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "pause"
  },
  {
    "featureId": "atomics-wait-async",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "waitAsync"
  },
  {
    "featureId": "bigint64array",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "BigInt64Array"
  },
  {
    "featureId": "bigint64array",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "BigUint64Array"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "@@toPrimitive"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "Date"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "UTC"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getDate"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getDay"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getFullYear"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getHours"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getMilliseconds"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getMinutes"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getMonth"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getSeconds"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getTime"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getTimezoneOffset"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getUTCDate"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getUTCDay"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getUTCFullYear"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getUTCHours"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getUTCMilliseconds"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getUTCMinutes"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getUTCMonth"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getUTCSeconds"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "now"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "parse"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setDate"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setFullYear"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setHours"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setMilliseconds"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setMinutes"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setMonth"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setSeconds"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setTime"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setUTCDate"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setUTCFullYear"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setUTCHours"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setUTCMilliseconds"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setUTCMinutes"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setUTCMonth"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setUTCSeconds"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toDateString"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toISOString"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toJSON"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toString"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toTimeString"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toUTCString"
  },
  {
    "featureId": "date",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "valueOf"
  },
  {
    "featureId": "date-get-year-set-year",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "getYear"
  },
  {
    "featureId": "date-get-year-set-year",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "setYear"
  },
  {
    "featureId": "date-to-gmt-string",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toGMTString"
  },
  {
    "featureId": "float16array",
    "kind": "instanceMember",
    "iface": "Float16Array",
    "prop": "Float16Array"
  },
  {
    "featureId": "float16array",
    "kind": "callStatic",
    "base": "Math",
    "prop": "f16round"
  },
  {
    "featureId": "getorinsert",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "getOrInsert"
  },
  {
    "featureId": "getorinsert",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "getOrInsertComputed"
  },
  {
    "featureId": "getorinsert",
    "kind": "instanceMember",
    "iface": "WeakMap",
    "prop": "getOrInsert"
  },
  {
    "featureId": "getorinsert",
    "kind": "instanceMember",
    "iface": "WeakMap",
    "prop": "getOrInsertComputed"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "anchor"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "big"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "blink"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "bold"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "fixed"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "fontcolor"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "fontsize"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "italics"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "link"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "small"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "strike"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "sub"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "substr"
  },
  {
    "featureId": "html-wrapper-methods",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "sup"
  },
  {
    "featureId": "intl",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "toLocaleString"
  },
  {
    "featureId": "intl",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toLocaleDateString"
  },
  {
    "featureId": "intl",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toLocaleString"
  },
  {
    "featureId": "intl",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toLocaleTimeString"
  },
  {
    "featureId": "intl",
    "kind": "newMember",
    "base": "Intl",
    "prop": "Collator"
  },
  {
    "featureId": "intl",
    "kind": "newMember",
    "base": "Intl",
    "prop": "DateTimeFormat"
  },
  {
    "featureId": "intl",
    "kind": "newMember",
    "base": "Intl",
    "prop": "NumberFormat"
  },
  {
    "featureId": "intl",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "toLocaleString"
  },
  {
    "featureId": "intl",
    "kind": "callStatic",
    "base": "Object",
    "prop": "toLocaleString"
  },
  {
    "featureId": "intl",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "localeCompare"
  },
  {
    "featureId": "intl",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "toLocaleLowerCase"
  },
  {
    "featureId": "intl",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "toLocaleUpperCase"
  },
  {
    "featureId": "intl-display-names",
    "kind": "newMember",
    "base": "Intl",
    "prop": "DisplayNames"
  },
  {
    "featureId": "intl-duration-format",
    "kind": "newMember",
    "base": "Intl",
    "prop": "DurationFormat"
  },
  {
    "featureId": "intl-list-format",
    "kind": "newMember",
    "base": "Intl",
    "prop": "ListFormat"
  },
  {
    "featureId": "intl-locale",
    "kind": "newMember",
    "base": "Intl",
    "prop": "Locale"
  },
  {
    "featureId": "intl-plural-rules",
    "kind": "newMember",
    "base": "Intl",
    "prop": "PluralRules"
  },
  {
    "featureId": "intl-relative-time-format",
    "kind": "newMember",
    "base": "Intl",
    "prop": "RelativeTimeFormat"
  },
  {
    "featureId": "intl-segmenter",
    "kind": "newMember",
    "base": "Intl",
    "prop": "Segmenter"
  },
  {
    "featureId": "javascript",
    "kind": "instanceMember",
    "iface": "Boolean",
    "prop": "Boolean"
  },
  {
    "featureId": "javascript",
    "kind": "instanceMember",
    "iface": "Boolean",
    "prop": "toString"
  },
  {
    "featureId": "javascript",
    "kind": "instanceMember",
    "iface": "Boolean",
    "prop": "valueOf"
  },
  {
    "featureId": "json",
    "kind": "callStatic",
    "base": "JSON",
    "prop": "json_superset"
  },
  {
    "featureId": "json",
    "kind": "callStatic",
    "base": "JSON",
    "prop": "parse"
  },
  {
    "featureId": "json",
    "kind": "callStatic",
    "base": "JSON",
    "prop": "stringify"
  },
  {
    "featureId": "json-raw",
    "kind": "callStatic",
    "base": "JSON",
    "prop": "isRawJSON"
  },
  {
    "featureId": "json-raw",
    "kind": "callStatic",
    "base": "JSON",
    "prop": "rawJSON"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "@@iterator"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "@@species"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "Map"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "clear"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "delete"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "entries"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "forEach"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "get"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "has"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "key_equality_for_zeros"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "keys"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "set"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "size"
  },
  {
    "featureId": "map",
    "kind": "instanceMember",
    "iface": "Map",
    "prop": "values"
  },
  {
    "featureId": "math-sum-precise",
    "kind": "callStatic",
    "base": "Math",
    "prop": "sumPrecise"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "E"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "LN10"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "LN2"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "LOG10E"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "LOG2E"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "PI"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "SQRT1_2"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "SQRT2"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "abs"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "acos"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "acosh"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "asin"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "asinh"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "atan"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "atan2"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "atanh"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "cbrt"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "ceil"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "clz32"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "cos"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "cosh"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "exp"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "expm1"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "floor"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "fround"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "hypot"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "imul"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "log"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "log10"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "log1p"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "log2"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "max"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "min"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "pow"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "random"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "round"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "sign"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "sin"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "sinh"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "sqrt"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "tan"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "tanh"
  },
  {
    "featureId": "number",
    "kind": "callStatic",
    "base": "Math",
    "prop": "trunc"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "EPSILON"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "MAX_SAFE_INTEGER"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "MAX_VALUE"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "MIN_SAFE_INTEGER"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "MIN_VALUE"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "NEGATIVE_INFINITY"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "NaN"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "Number"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "POSITIVE_INFINITY"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "isFinite"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "isInteger"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "isNaN"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "isSafeInteger"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "parseFloat"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "parseInt"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "toExponential"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "toFixed"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "toPrecision"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "toString"
  },
  {
    "featureId": "number",
    "kind": "instanceMember",
    "iface": "Number",
    "prop": "valueOf"
  },
  {
    "featureId": "object-hasown",
    "kind": "callStatic",
    "base": "Object",
    "prop": "hasOwn"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "Object"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "assign"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "constructor"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "create"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "defineProperties"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "defineProperty"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "entries"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "freeze"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "fromEntries"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "getOwnPropertyDescriptor"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "getOwnPropertyDescriptors"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "getOwnPropertyNames"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "getOwnPropertySymbols"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "getPrototypeOf"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "hasOwnProperty"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "is"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "isExtensible"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "isFrozen"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "isPrototypeOf"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "isSealed"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "keys"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "preventExtensions"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "propertyIsEnumerable"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "seal"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "setPrototypeOf"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "toString"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "valueOf"
  },
  {
    "featureId": "object-object",
    "kind": "callStatic",
    "base": "Object",
    "prop": "values"
  },
  {
    "featureId": "promise",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "@@species"
  },
  {
    "featureId": "promise",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "Promise"
  },
  {
    "featureId": "promise",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "all"
  },
  {
    "featureId": "promise",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "catch"
  },
  {
    "featureId": "promise",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "incumbent_settings_object_tracking"
  },
  {
    "featureId": "promise",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "race"
  },
  {
    "featureId": "promise",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "reject"
  },
  {
    "featureId": "promise",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "resolve"
  },
  {
    "featureId": "promise",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "then"
  },
  {
    "featureId": "promise-allsettled",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "allSettled"
  },
  {
    "featureId": "promise-any",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "any"
  },
  {
    "featureId": "promise-finally",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "finally"
  },
  {
    "featureId": "promise-try",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "try"
  },
  {
    "featureId": "promise-withresolvers",
    "kind": "instanceMember",
    "iface": "Promise",
    "prop": "withResolvers"
  },
  {
    "featureId": "proto",
    "kind": "callStatic",
    "base": "Object",
    "prop": "proto"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "apply"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "construct"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "defineProperty"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "deleteProperty"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "get"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "getOwnPropertyDescriptor"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "getPrototypeOf"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "has"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "isExtensible"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "ownKeys"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "preventExtensions"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "set"
  },
  {
    "featureId": "proxy-reflect",
    "kind": "callStatic",
    "base": "Reflect",
    "prop": "setPrototypeOf"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "@@match"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "@@matchAll"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "@@replace"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "@@search"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "@@species"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "@@split"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "RegExp"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "dotAll"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "exec"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "flags"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "global"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "hasIndices"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "ignoreCase"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "lastIndex"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "multiline"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "source"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "sticky"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "test"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "toString"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "unicode"
  },
  {
    "featureId": "regexp",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "unicodeSets"
  },
  {
    "featureId": "regexp-compile",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "compile"
  },
  {
    "featureId": "regexp-escape",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "escape"
  },
  {
    "featureId": "regexp-static-properties",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "input"
  },
  {
    "featureId": "regexp-static-properties",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "lastMatch"
  },
  {
    "featureId": "regexp-static-properties",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "lastParen"
  },
  {
    "featureId": "regexp-static-properties",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "leftContext"
  },
  {
    "featureId": "regexp-static-properties",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "n"
  },
  {
    "featureId": "regexp-static-properties",
    "kind": "instanceMember",
    "iface": "RegExp",
    "prop": "rightContext"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "@@iterator"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "@@species"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "Set"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "add"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "clear"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "delete"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "entries"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "forEach"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "has"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "key_equality_for_zeros"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "keys"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "size"
  },
  {
    "featureId": "set",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "values"
  },
  {
    "featureId": "set-methods",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "difference"
  },
  {
    "featureId": "set-methods",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "intersection"
  },
  {
    "featureId": "set-methods",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "isDisjointFrom"
  },
  {
    "featureId": "set-methods",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "isSubsetOf"
  },
  {
    "featureId": "set-methods",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "isSupersetOf"
  },
  {
    "featureId": "set-methods",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "symmetricDifference"
  },
  {
    "featureId": "set-methods",
    "kind": "instanceMember",
    "iface": "Set",
    "prop": "union"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "Atomic_operations_on_non_shared_buffers"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "add"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "and"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "compareExchange"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "exchange"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "isLockFree"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "load"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "notify"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "or"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "store"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "sub"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "wait"
  },
  {
    "featureId": "shared-memory",
    "kind": "callStatic",
    "base": "Atomics",
    "prop": "xor"
  },
  {
    "featureId": "string-at",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "at"
  },
  {
    "featureId": "string-codepoint",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "codePointAt"
  },
  {
    "featureId": "string-codepoint",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "fromCodePoint"
  },
  {
    "featureId": "string-includes",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "includes"
  },
  {
    "featureId": "string-matchall",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "matchAll"
  },
  {
    "featureId": "string-normalize",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "normalize"
  },
  {
    "featureId": "string-pad",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "padEnd"
  },
  {
    "featureId": "string-pad",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "padStart"
  },
  {
    "featureId": "string-raw",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "raw"
  },
  {
    "featureId": "string-repeat",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "repeat"
  },
  {
    "featureId": "string-replaceall",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "replaceAll"
  },
  {
    "featureId": "string-startsends-with",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "endsWith"
  },
  {
    "featureId": "string-startsends-with",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "startsWith"
  },
  {
    "featureId": "string-trim-startend",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "trimEnd"
  },
  {
    "featureId": "string-trim-startend",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "trimStart"
  },
  {
    "featureId": "string-wellformed",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "isWellFormed"
  },
  {
    "featureId": "string-wellformed",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "toWellFormed"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "@@iterator"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "String"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "charAt"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "charCodeAt"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "concat"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "fromCharCode"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "indexOf"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "lastIndexOf"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "length"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "match"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "replace"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "search"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "slice"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "split"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "substring"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "toLowerCase"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "toString"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "toUpperCase"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "trim"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "unicode_code_point_escapes"
  },
  {
    "featureId": "strings",
    "kind": "instanceMember",
    "iface": "String",
    "prop": "valueOf"
  },
  {
    "featureId": "symbol",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "@@species"
  },
  {
    "featureId": "temporal",
    "kind": "instanceMember",
    "iface": "Date",
    "prop": "toTemporalInstant"
  },
  {
    "featureId": "temporal",
    "kind": "newMember",
    "base": "Temporal",
    "prop": "Duration"
  },
  {
    "featureId": "temporal",
    "kind": "newMember",
    "base": "Temporal",
    "prop": "Instant"
  },
  {
    "featureId": "temporal",
    "kind": "newMember",
    "base": "Temporal",
    "prop": "PlainDate"
  },
  {
    "featureId": "temporal",
    "kind": "newMember",
    "base": "Temporal",
    "prop": "PlainDateTime"
  },
  {
    "featureId": "temporal",
    "kind": "newMember",
    "base": "Temporal",
    "prop": "PlainMonthDay"
  },
  {
    "featureId": "temporal",
    "kind": "newMember",
    "base": "Temporal",
    "prop": "PlainTime"
  },
  {
    "featureId": "temporal",
    "kind": "newMember",
    "base": "Temporal",
    "prop": "PlainYearMonth"
  },
  {
    "featureId": "temporal",
    "kind": "newMember",
    "base": "Temporal",
    "prop": "ZonedDateTime"
  },
  {
    "featureId": "typed-arrays",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "Float32Array"
  },
  {
    "featureId": "typed-arrays",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "Float64Array"
  },
  {
    "featureId": "typed-arrays",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "Int16Array"
  },
  {
    "featureId": "typed-arrays",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "Int32Array"
  },
  {
    "featureId": "typed-arrays",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "Int8Array"
  },
  {
    "featureId": "weakmap",
    "kind": "instanceMember",
    "iface": "WeakMap",
    "prop": "WeakMap"
  },
  {
    "featureId": "weakmap",
    "kind": "instanceMember",
    "iface": "WeakMap",
    "prop": "delete"
  },
  {
    "featureId": "weakmap",
    "kind": "instanceMember",
    "iface": "WeakMap",
    "prop": "get"
  },
  {
    "featureId": "weakmap",
    "kind": "instanceMember",
    "iface": "WeakMap",
    "prop": "has"
  },
  {
    "featureId": "weakmap",
    "kind": "instanceMember",
    "iface": "WeakMap",
    "prop": "set"
  },
  {
    "featureId": "weakmap",
    "kind": "instanceMember",
    "iface": "WeakMap",
    "prop": "symbol_as_keys"
  },
  {
    "featureId": "weakset",
    "kind": "instanceMember",
    "iface": "WeakSet",
    "prop": "WeakSet"
  },
  {
    "featureId": "weakset",
    "kind": "instanceMember",
    "iface": "WeakSet",
    "prop": "add"
  },
  {
    "featureId": "weakset",
    "kind": "instanceMember",
    "iface": "WeakSet",
    "prop": "delete"
  },
  {
    "featureId": "weakset",
    "kind": "instanceMember",
    "iface": "WeakSet",
    "prop": "has"
  },
  {
    "featureId": "weakset",
    "kind": "instanceMember",
    "iface": "WeakSet",
    "prop": "symbol_as_keys"
  },
  {
    "featureId": "with",
    "kind": "instanceMember",
    "iface": "Array",
    "prop": "@@unscopables"
  },
  {
    "featureId": "error-cause",
    "kind": "newWithOptions",
    "name": "Error",
    "objectArg": {
      "index": 1,
      "hasKeys": [
        "cause"
      ]
    }
  },
  {
    "featureId": "error-cause",
    "kind": "newWithOptions",
    "name": "AggregateError",
    "objectArg": {
      "index": 2,
      "hasKeys": [
        "cause"
      ]
    }
  },
  {
    "featureId": "explicit-resource-management",
    "kind": "newIdent",
    "name": "DisposableStack"
  },
  {
    "featureId": "explicit-resource-management",
    "kind": "member",
    "base": "Symbol",
    "prop": "dispose"
  },
  {
    "featureId": "explicit-resource-management",
    "kind": "member",
    "base": "Symbol",
    "prop": "asyncDispose"
  },
  {
    "featureId": "is-error",
    "kind": "callStatic",
    "base": "Error",
    "prop": "isError"
  },
  {
    "featureId": "resizable-buffers",
    "kind": "newWithOptions",
    "name": "ArrayBuffer",
    "objectArg": {
      "index": 1,
      "hasKeys": [
        "maxByteLength"
      ]
    }
  },
  {
    "featureId": "resizable-buffers",
    "kind": "newWithOptions",
    "name": "SharedArrayBuffer",
    "objectArg": {
      "index": 1,
      "hasKeys": [
        "maxByteLength",
        "growable"
      ]
    },
    "typedOnly": true
  },
  {
    "featureId": "uint8array-base64-hex",
    "kind": "callStatic",
    "base": "Uint8Array",
    "prop": "fromBase64"
  },
  {
    "featureId": "uint8array-base64-hex",
    "kind": "callStatic",
    "base": "Uint8Array",
    "prop": "fromHex"
  },
  {
    "featureId": "uint8array-base64-hex",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "toBase64"
  },
  {
    "featureId": "uint8array-base64-hex",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "toHex"
  },
  {
    "featureId": "weak-references",
    "kind": "newIdent",
    "name": "WeakRef"
  },
  {
    "featureId": "weak-references",
    "kind": "newIdent",
    "name": "FinalizationRegistry"
  },
  {
    "featureId": "intl-locale-info",
    "kind": "newMember",
    "base": "Intl",
    "prop": "Locale"
  },
  {
    "featureId": "intl-locale-info",
    "kind": "instanceMember",
    "iface": "Locale",
    "prop": "maximize"
  },
  {
    "featureId": "intl-locale-info",
    "kind": "instanceMember",
    "iface": "Locale",
    "prop": "minimize"
  },
  {
    "featureId": "intl-locale-info",
    "kind": "instanceMember",
    "iface": "Locale",
    "prop": "hourCycle"
  },
  {
    "featureId": "intl-locale-info",
    "kind": "instanceMember",
    "iface": "Locale",
    "prop": "textInfo"
  },
  {
    "featureId": "intl-locale-info",
    "kind": "instanceMember",
    "iface": "Locale",
    "prop": "weekInfo"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "map"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "filter"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "take"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "drop"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "flatMap"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "reduce"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "toArray"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "forEach"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "some"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "every"
  },
  {
    "featureId": "iterator-methods",
    "kind": "instanceMember",
    "iface": "Iterator",
    "prop": "find"
  },
  {
    "featureId": "intl-locale-info",
    "kind": "instanceMember",
    "iface": "Locale",
    "prop": "calendars"
  },
  {
    "featureId": "intl-locale-info",
    "kind": "instanceMember",
    "iface": "Locale",
    "prop": "collations"
  },
  {
    "featureId": "intl-locale-info",
    "kind": "instanceMember",
    "iface": "Locale",
    "prop": "numberingSystems"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "entries"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "keys"
  },
  {
    "featureId": "typed-array-iterators",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "values"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int8Array",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8Array",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint8ClampedArray",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int16Array",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint16Array",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Int32Array",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Uint32Array",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float32Array",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "Float64Array",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigInt64Array",
    "prop": "findIndex"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "every"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "some"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "forEach"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "map"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "filter"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "reduce"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "reduceRight"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "find"
  },
  {
    "featureId": "typed-array-iteration-methods",
    "kind": "instanceMember",
    "iface": "BigUint64Array",
    "prop": "findIndex"
  }
];
export default descriptors;
